<?php

/**
 * @file
 * Fullcalendar customizations for OpenScholar.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function os_fullcalendar_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_events_edit_form' || $form_id == 'node_events_form') {
    // Markup for repeating event warning message.
    $form['field_recurring_date']['widget'][0]['repeat_event_change_message'] = [
      '#markup' => '<div id="event-change-notify" class="messages messages--warning visually-hidden">' . t("You will need to inform the registrants if you make any changes to this event. If you change the date, registrants will be removed and will have to re-register.") . '</div>',
      '#weight' => 1,
    ];

    $form['#attached']['library'][] = 'os_fullcalendar/drupal.os_fullcalendar';
  }

}
