<?php

/**
 * @file
 * Hooks Implementations.
 */

/**
 * Implements hook_toolbar_alter().
 *
 * Hides the administration toolbar unless the user has access to see it.
 */
function cp_toolbar_alter(&$toolbar) {
  // Prevent the Admin menu toolbar tray from appearing
  // to users who don't have permission to do anything with it.
  if (!\Drupal::currentUser()->hasPermission('access administration pages')) {

    if (isset($toolbar['toolbar_menu_control_panel'])) {
      $toolbar['toolbar_menu_control_panel']['tray']['#attached'] = $toolbar['administration']['tray']['#attached'];
      $combined_libraries = array_merge_recursive($toolbar['toolbar_menu_control_panel']['#attached'], $toolbar['administration']['#attached']);
      $toolbar['toolbar_menu_control_panel']['#attached'] = $combined_libraries;
    }

    unset($toolbar['administration']);
  }
}
