<?php

/**
 * @file
 * Hook implementations for the os module.
 */

/**
 * Implements hook_library_info_alter().
 */
function os_library_info_alter(&$libraries, $extension) {
  if ($extension == 'core') {
    return;
  }

  /** @var \Drupal\Core\Extension\ModuleHandlerInterface $moduleHandler */
  $moduleHandler = \Drupal::service('module_handler');

  // Filter out themes and profiles or whatever. only modules.
  if (!$moduleHandler->moduleExists($extension)) {
    return;
  }
  $path = drupal_get_path('module', $extension);

  foreach ($libraries as $name => &$lib) {
    if (isset($lib['paths'])) {
      if (strpos($lib['paths'], '/') === 0) {
        $lib['drupalSettings']['paths'][$name] = ltrim($lib['paths'], '/') . '/';
      }
      else {
        $lib['drupalSettings']['paths'][$name] = $path . '/' . $lib['paths'] . '/';
      }
    }
  }
}

/**
 * Implements hook_preprocess_html().
 */
function os_preprocess_html(&$variables) {
  /** @var \Drupal\os\AngularModuleManagerInterface $ngModuleManager */
  $ngModuleManager = \Drupal::service('angular.module_manager');
  if ($modules = $ngModuleManager->getModules()) {
    $variables['attributes']['ng-app'] = 'openscholar';
    $variables['attributes']['data-ng-modules'] = implode(',', $modules);
    $variables['#attached']['library'][] = 'os/openscholarModule';
  }
}

/**
 * Implements hook_preprocess_block().
 *
 * Replaces 'Drupal' with 'OpenScholar' in the powered by block.
 *
 * @param array $vars
 */
function os_preprocess_block(&$vars) {
  if (isset($vars['plugin_id']) && $vars['plugin_id'] == 'system_powered_by_block') {
    $vars['content']['#markup'] = '';
    if (\Drupal::currentUser()->isAnonymous()) {
      $vars['content']['#markup'] .= \Drupal\Core\Link::createFromRoute(t('Admin Login'), 'user.login', [], ['query' => \Drupal::destination()->getAsArray()])->toString();
    }
    $vars['content']['#markup'] .= t('<span id="powered-by">Powered by <a href=":link">OpenScholar</a></span>', [':link' => 'https://theopenscholar.com/']);
  }
}
