<?php

namespace Drupal\os_widgets;

use Drupal\Core\Config\Entity\ConfigEntityListBuilder;
use Drupal\Core\Entity\EntityInterface;

/**
 * List builder for the LayoutContext entities.
 */
class LayoutContextListBuilder extends ConfigEntityListBuilder {

  /**
   * {@inheritdoc}
   */
  public function buildHeader() {
    $header = [];

    $header['label'] = $this->t('Label');
    $header['description'] = $this->t('Description');

    // TODO: Change the autogenerated stub.
    $header += parent::buildHeader();

    return $header;
  }

  /**
   * {@inheritdoc}
   */
  public function buildRow(EntityInterface $entity) {
    $row = [];

    $row['label'] = $entity->label();
    $row['description']['data'] = ['#markup' => $entity->getDescription()];

    $row += parent::buildRow($entity);

    return $row;
  }

}
