<?php

namespace Drupal\os_widgets;


use Drupal\Core\Config\Entity\ConfigEntityListBuilder;
use Drupal\Core\Entity\EntityInterface;

class LayoutContextListBuilder extends ConfigEntityListBuilder {

  public function buildHeader() {
    $header = [];

    $header['label'] = $this->t('Label');
    $header['description'] = $this->t('Description');

    $header += parent::buildHeader(); // TODO: Change the autogenerated stub

    return $header;
  }

  public function buildRow(EntityInterface $entity) {
    $row = [];

    $row['label'] = $entity->label().'test';
    $row['description']['data'] = ['#markup' => $entity->getDescription()];

    $row += parent::buildRow($entity);

    return $row;
  }

}
