<?php

/**
 * @file
 * OS widgets.
 */

/**
 * Implements hook_entity_type_alter().
 */
function os_widgets_entity_type_alter(array &$entity_types) {
  $entity_types['block_content']->setHandlerClass('view_builder', 'Drupal\os_widgets\OsBlockContentViewBuilder');
}

/**
 * Implements hook_preprocess_node().
 */
function os_widgets_preprocess_node(&$variables) {
  if (!empty($variables['elements']['os_widgets_hide_node_title'])) {
    $variables['label']['#access'] = FALSE;
  }
}
