<?php

/**
 * @file
 * Pages app.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\block_visibility_groups\Entity\BlockVisibilityGroup;

/**
 * Implements hook_entity_insert().
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function os_pages_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityType()->id() === 'node' && $entity->bundle() === 'page') {
    /** @var \Drupal\block_visibility_groups\Entity\BlockVisibilityGroup $bvg */
    $bvg = BlockVisibilityGroup::create([
      'id' => 'os_pages_' . rand(1, 1000),
      'label' => t('OS Pages'),
      'status' => TRUE,
      'allow_other_conditions' => TRUE,
    ]);

    $bvg->save();

    $bvg->addCondition([
      'id' => 'request_path',
      'pages' => '/node/*',
      'negate' => 0,
    ]);

    $bvg->save();
  }
}
