<?php

namespace Drupal\Tests\vsite\Kernel;


use Drupal\KernelTests\KernelTestBase;

/**
 * Class AppManagerTest
 * @package Drupal\Tests\vsite\Kernel\
 */
class AppManagerTest extends KernelTestBase {

  public function setUp() {
    parent::setUp(); // TODO: Change the autogenerated stub
  }

  public function testSilence() {
    $i = null;
    $this->assertNull($i);
  }
}