<?php

namespace Drupal\Tests\vsite\Kernel;

use Drupal\KernelTests\KernelTestBase;

/**
 * Class AppManagerTest.
 *
 * @package Drupal\Tests\vsite\Kernel\
 * @group kernel
 */
class AppManagerTest extends KernelTestBase {

  /**
   * {@inheritdoc}
   */
  public function setUp() {
    // TODO: Change the autogenerated stub.
    parent::setUp();
  }

  /**
   * Nothing.
   */
  public function testSilence() {
    $i = NULL;
    $this->assertNull($i);
  }

}
