<?php

/**
 * @file
 * Hook implementations and stand-alone callbacks.
 */

/**
 * Returns a list of allowed privacy options.
 *
 * @return mixed
 *   An array of acceptable options for the privacy_level field.
 */
function vsite_privacy_allowed_values() {
  /** @var \Drupal\vsite_privacy\Plugin\VsitePrivacyLevelManagerInterface $vsite_privacy_manager */
  $vsite_privacy_manager = \Drupal::service('vsite.privacy.manager');
  return $vsite_privacy_manager->getOptions();
}
