<?php

/**
 * @file
 * Hook implementations and stand-alone callbacks.
 */

/**
 * Returns a list of allowed privacy options.
 *
 * @return mixed
 *   An array of acceptable options for the privacy_level field.
 */
function vsite_privacy_allowed_values() {
  /** @var \Drupal\vsite_privacy\Plugin\VsitePrivacyLevelManagerInterface $vsite_privacy_manager */
  $vsite_privacy_manager = \Drupal::service('vsite.privacy.manager');
  return $vsite_privacy_manager->getOptions();
}

/**
 * Implements hook_robotstxt().
 */
function vsite_privacy_robotstxt() {

  /** @var \Drupal\Core\Config\ImmutableConfig $os_publication_settings */
  $os_publication_settings = \Drupal::config('vsite_privacy.settings');
  $robots_settings = $os_publication_settings->get('robotstxt_directives');
  if (empty($robots_settings)) {
    return [];
  }
  $host = \Drupal::request()->getHost();
  if (isset($robots_settings[$host])) {
    return $robots_settings[$host];
  }
  return [];
}
