<?php

/**
 * Implements hook_library.
 */
function os_node_form_library() {
  $libs = array();
  $self = drupal_get_path('module', 'os_node_form');
  $disable = array('alias' => TRUE);

  $libs['os-node-form'] = array(
    'title' => 'OS node form angular',
    'js' => array(
      libraries_get_path('ckeditor') . '/ckeditor.js' => array(),
      $self.'/osNodeForm.module.js' => array(),
      array(
        'data' => array(
          'paths' => array(
            'osNodeForm' => url($self.'/templates', $disable),
          ),
        ),
        'type' => 'setting',
      )
    ),
    'dependencies' => array(
      array('os_common', 'angular-modal-service'),
      array('os_common', 'formElement'),
      array('os_common', 'buttonSpinner'),
    )
  );

  return $libs;
}

/**
  * Implements hook_preprocess_page().
  *
  * Adds the content-add-form angular library.
 */
function os_node_form_preprocess_page(&$vars) {
  if (user_is_logged_in() && variable_get('admin_panel_enabled', FALSE)) {
    drupal_add_library('os_node_form', 'os-node-form');
    $profile = wysiwyg_get_profile('filtered_html');
    wysiwyg_add_plugin_settings($profile);
    //dpm(wysiwyg_add_plugin_settings($profile));
  }
}

/**
 * Implements hook_js_alter.
 *
 * Support Drupal wysiwyg ckeditor along with angular ckeditor.
 */
function os_node_form_js_alter(&$javascript) {
  $javascript['profiles/openscholar/libraries/ckeditor/ckeditor.js']['weight'] = -10;
}

