<?php
/**
 * include css file for template()
 */
drupal_add_css(drupal_get_path('module', 'os_landing_page').'/includes/frontpage.css', array('group' => CSS_THEME,'weight' => '999'));
 
/**
 * Implements hook_menu()
 */
function os_landing_page_menu() {
  $items = array();
  $items['os/frontpage'] = array(
    'page callback' => 'os_landing_page',
    'access callback' => TRUE,
    'file' => 'frontpage.inc',
    'file path' => drupal_get_path('module', 'os_landing_page').'/includes',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function os_landing_page_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path( 'module', 'os_landing_page');
  return array(
    'os_landing_page_template' => array(
      'template' => 'os_landing_page',
      'variables' => array(),
      'path' => $path . '/templates',
    ),
  );
}

/**
 * Implements hook_css_alter().
 */
function os_landing_page_css_alter(&$css) {
  global $user;
  $args = arg();
  if($user->uid == 0 && $args[0] == 'os' && $args[1] == 'frontpage'){
    $path = path_to_theme();
    foreach($css as $key => $file){
      if (strpos($key, $path) !== false) {
        unset($css[$key]);
      }
    }
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function os_landing_page_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_strongarm().
 */
function os_landing_page_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE;
  $strongarm->api_version = 1;
  $strongarm->name = 'path_to_school_main_website';
  $strongarm->value = 'http://web.mit.edu/';
  $export['path_to_school_main_website'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE;
  $strongarm->api_version = 1;
  $strongarm->name = 'path_to_logo';
  $strongarm->value = 'http://www.communityactionschool.org/files/news/mit_logo.png';
  $export['path_to_logo'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE;
  $strongarm->api_version = 1;
  $strongarm->name = 'name_of_school';
  $strongarm->value = 'School Name';
  $export['name_of_school'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE;
  $strongarm->api_version = 1;
  $strongarm->name = 'path_to_schools_accessibility_policy';
  $strongarm->value = 'http://www.google.com';
  $export['path_to_schools_accessibility_policy'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE;
  $strongarm->api_version = 1;
  $strongarm->name = 'path_to_schools_reporting_copyright_infringements';
  $strongarm->value = 'http://www.google.com';
  $export['path_to_schools_reporting_copyright_infringements'] = $strongarm;

  return $export;
}