<?php

/**
 * @file
 * Theme preview hooks.
 */

use Drupal\os_theme_preview\Form\PreviewAction;

/**
 * Implements hook_page_bottom().
 */
function os_theme_preview_page_bottom(array &$page_bottom) {
  /** @var \Drupal\os_theme_preview\PreviewManagerInterface $preview_manager */
  $preview_manager = \Drupal::service('os_theme_preview.manager');

  if (!$preview_manager->isPreviewModeEnabled()) {
    return;
  }

  /** @var array $preview_action_form */
  $preview_action_form = \Drupal::formBuilder()->getForm(PreviewAction::class);

  $page_bottom['preview_action_form'] = $preview_action_form;
}
