<?php

/**
 * @file
 * Theme preview hooks.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\os_theme_preview\ThemePreviewException;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function os_theme_preview_form_system_themes_admin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['preview'] = [
    '#type' => 'button',
    '#value' => t('Preview'),
    '#executes_submit_callback' => TRUE,
  ];
  $form['#submit'][] = 'os_theme_preview_theme_preview_action';

  /** @var \Drupal\os_theme_preview\HelperInterface $helper */
  $helper = \Drupal::service('os_theme_preview.helper');

  /** @var \Drupal\os_theme_preview\ThemePreview|null $previewed_theme_data */
  $previewed_theme_data = $helper->getPreviewedThemeData();
  if (!$previewed_theme_data) {
    return;
  }

  /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsite_context_manager */
  $vsite_context_manager = \Drupal::service('vsite.context_manager');
  /** @var \Drupal\group\Entity\GroupInterface|null $group */
  $group = $vsite_context_manager->getActiveVsite();

  if ($group) {
    $is_preview_enabled = ($previewed_theme_data->getVsiteId() === (int) $group->id());
  }
  else {
    $is_preview_enabled = ($previewed_theme_data->getVsiteId() === 0);
  }

  if (!$is_preview_enabled) {
    return;
  }

  $form['cancel_preview'] = [
    '#type' => 'button',
    '#value' => t('Cancel Preview'),
    '#executes_submit_callback' => TRUE,
  ];
}

/**
 * Starts the theme preview.
 */
function os_theme_preview_theme_preview_action(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\os_theme_preview\HelperInterface $helper */
  $helper = \Drupal::service('os_theme_preview.helper');

  try {
    $op = $form_state->getValue('op')->__toString();

    if ($op === 'Preview') {
      /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsite_context_manager */
      $vsite_context_manager = \Drupal::service('vsite.context_manager');
      /** @var \Drupal\group\Entity\GroupInterface|null $group */
      $group = $vsite_context_manager->getActiveVsite();
      $theme = 'hwpi_themeone_bentley';

      if ($group) {
        $helper->startPreviewMode($theme, $group->id());
      }
      else {
        $helper->startPreviewMode($theme, 0);
      }
    }
    elseif ($op === 'Cancel Preview') {
      $helper->stopPreviewMode();
    }
  }
  catch (ThemePreviewException $e) {
    /** @var \Drupal\Core\Messenger\MessengerInterface $messenger */
    $messenger = \Drupal::messenger();
    $messenger->addError($e->getMessage());
  }
}
