<?php

/**
 * @file
 * Software project customizations for Openscholar.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function os_software_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_software_project_form' || $form_id == 'node_software_project_edit_form') {
    $form['field_packaging']['widget'] = [
      '#markup' => '<div class="form-item form-type-textfield form-item-title"><label> ' . t("Packaging Method") . '<span class="form-required" title="This field is required."></span></lable><div class="no-bold">' . t("Manual upload") . '</div></div>',
      '#weight' => 1,
    ];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function os_software_form_node_software_release_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  _os_software_hide_node_title_form($form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function os_software_form_node_software_release_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  _os_software_hide_node_title_form($form);
}

/**
 * Hide title in form.
 */
function _os_software_hide_node_title_form(&$form) {
  $form['title']['#access'] = FALSE;
}

/**
 * Implements hook_node_presave().
 *
 * Generates the node title for Software Releases.
 */
function os_software_node_presave($node) {
  if ($node->bundle() != 'software_release') {
    return;
  }

  // Sets the node title like "[project-node:title] [release-node:version]".
  /** @var \Drupal\os_software\OsSoftwareHelper $helper */
  $helper = Drupal::service('os.software.helper');
  $title = $helper->prepareReleaseTitle($node);
  $node->set('title', $title);
}
