<?php

/**
 * @file
 * Manages vsite roles.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\cp_roles\Controller\CpRoleListBuilder;
use Drupal\group\Entity\GroupRoleInterface;

/**
 * Implements hook_entity_presave().
 */
function cp_roles_entity_presave(EntityInterface $entity) {
  // Makes sure that the GroupRole ID contains the vsite ID where it was
  // created.
  if ($entity instanceof GroupRoleInterface && $entity->isNew()) {
    /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsite_context_manager */
    $vsite_context_manager = \Drupal::service('vsite.context_manager');
    /** @var \Drupal\group\Entity\GroupInterface|null $vsite */
    $vsite = $vsite_context_manager->getActiveVsite();

    if (!$vsite) {
      return;
    }

    $provided_entity_id = \str_replace("{$entity->getGroupTypeId()}-", '', $entity->id());

    $entity->set('id', "{$entity->getGroupTypeId()}-{$vsite->id()}_{$provided_entity_id}");
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cp_roles_form_group_role_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Performs alterations in the role-add form, so that it matches the
  // requirement of putting vsite ID in the GroupRole ID.
  /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsite_context_manager */
  $vsite_context_manager = \Drupal::service('vsite.context_manager');
  /** @var \Drupal\group\Entity\GroupInterface|null $vsite */
  $vsite = $vsite_context_manager->getActiveVsite();

  if (!$vsite) {
    return;
  }

  $subtract = \strlen($vsite->bundle()) + \strlen($vsite->id()) + 1;
  /** @var string $default_id_prefix */
  $default_id_prefix = $form['id']['#field_prefix'];

  $form['id']['#field_prefix'] = "$default_id_prefix{$vsite->id()}_";
  $form['id']['#maxlength'] = EntityTypeInterface::ID_MAX_LENGTH - $subtract;

  $form['actions']['submit']['#submit'][] = 'cp_roles_group_role_add_form_submit';
}

/**
 * Submit handler for group role add form.
 *
 * @ingroup forms
 */
function cp_roles_group_role_add_form_submit(array &$form, FormStateInterface $form_state) {
  $form_state->setRedirect('cp_roles.role.list');
}

/**
 * Implements hook_entity_type_build().
 */
function cp_roles_entity_type_build(array &$entity_types) {
  if (isset($entity_types['group_role'])) {
    /** @var \Drupal\Core\Config\Entity\ConfigEntityTypeInterface $group_role_type */
    $group_role_type = $entity_types['group_role'];
    $group_role_type->setListBuilderClass(CpRoleListBuilder::class);
  }
}
