<?php

/**
 * @file
 * Manages vsite roles.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\group\Entity\GroupRoleInterface;

/**
 * Implements hook_entity_presave().
 */
function cp_roles_entity_presave(EntityInterface $entity) {
  // Makes sure that the GroupRole ID contains the vsite ID where it was
  // created.
  if ($entity instanceof GroupRoleInterface && $entity->isNew()) {
    /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsite_context_manager */
    $vsite_context_manager = \Drupal::service('vsite.context_manager');
    /** @var \Drupal\group\Entity\GroupInterface|null $vsite */
    $vsite = $vsite_context_manager->getActiveVsite();

    if (!$vsite) {
      return;
    }

    $provided_entity_id = \str_replace("{$entity->getGroupTypeId()}-", '', $entity->id());

    $entity->set('id', "{$entity->getGroupTypeId()}-{$vsite->id()}-{$provided_entity_id}");
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cp_roles_form_group_role_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Performs alterations in the role-add form, so that it matches the
  // requirement of putting vsite ID in the GroupRole ID.
  /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsite_context_manager */
  $vsite_context_manager = \Drupal::service('vsite.context_manager');
  /** @var \Drupal\group\Entity\GroupInterface|null $vsite */
  $vsite = $vsite_context_manager->getActiveVsite();

  if (!$vsite) {
    return;
  }

  $subtract = \strlen($vsite->bundle()) + \strlen($vsite->id()) + 1;
  /** @var string $default_id_prefix */
  $default_id_prefix = $form['id']['#field_prefix'];

  $form['id']['#field_prefix'] = "$default_id_prefix{$vsite->id()}-";
  $form['id']['#maxlength'] = EntityTypeInterface::ID_MAX_LENGTH - $subtract;
}
