<?php

/**
 * @file
 * Hook implementations for the cp_taxonomy module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\cp_taxonomy\CpTaxonomyHelper;
use Drupal\Core\Session\AccountInterface;
use Drupal\cp_taxonomy\Plugin\Field\FieldWidget\TaxonomyTermsWidget;
use Drupal\views\ViewExecutable;
use Drupal\vsite\Config\HierarchicalStorage;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_entity_operation_alter().
 *
 * Remove operations from taxonomy vocabs we don't care about.
 *
 * @param array $operations
 *   List of operations.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity these operations will act on.
 */
function cp_taxonomy_entity_operation_alter(array &$operations, EntityInterface $entity) {
  /** @var \Drupal\vsite\Plugin\VsiteContextManagerInterface $vsiteContextManager */
  $vsiteContextManager = \Drupal::service('vsite.context_manager');
  if ($vsiteContextManager->getActiveVsite()) {
    if ($entity->getEntityTypeId() == 'taxonomy_vocabulary') {
      $keys = [
        'edit' => 'cp.taxonomy.edit',
        'list' => 'cp.taxonomy.list',
        'add' => 'cp.taxonomy.term.add',
      ];
      $operations = array_intersect_key($operations, $keys);
      foreach ($keys as $key => $route_name) {
        if (empty($operations[$key]['url'])) {
          continue;
        }
        /** @var \Drupal\Core\Url $url */
        $url = $operations[$key]['url'];
        $operations[$key]['url'] = Url::fromRoute($route_name, $url->getRouteParameters());
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Remove global vocabularies from the list.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function cp_taxonomy_form_taxonomy_overview_vocabularies_alter(array &$form, FormStateInterface $form_state) {
  if (\Drupal::routeMatch()->getRouteName() == 'cp.taxonomy') {
    /** @var \Drupal\vsite\Config\HierarchicalStorageInterface $storage */
    $storage = \Drupal::service('hierarchical.storage');
    $globalVocabs = $storage->listAllFromLevel('taxonomy.vocabulary.', HierarchicalStorage::GLOBAL_STORAGE);
    $globalVocabs = str_replace('taxonomy.vocabulary.', '', $globalVocabs);
    $keyed = array_flip($globalVocabs);
    $form['vocabularies'] = array_diff_key($form['vocabularies'], $keyed);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add our submit handler to the form.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function cp_taxonomy_form_taxonomy_vocabulary_form_alter(array &$form, FormStateInterface &$form_state) {
  if (\Drupal::routeMatch()->getRouteName() == 'cp.taxonomy.add') {
    $form['actions']['submit']['#submit'][] = 'cp_taxonomy_form_add_vocab_submit';
  }
  elseif (\Drupal::routeMatch()->getRouteName() == 'cp.taxonomy.edit') {
    /** @var \Drupal\Core\Url $url */
    $url = $form['actions']['delete']['#url'];
    $form['actions']['delete']['#url'] = Url::fromRoute('cp.taxonomy.delete', $url->getRouteParameters());
    $form['actions']['submit']['#submit'][] = 'cp_taxonomy_form_add_vocab_submit';
  }
  /** @var \Drupal\cp_taxonomy\CpTaxonomyHelperInterface $taxonomy_helper */
  $taxonomy_helper = Drupal::service('cp.taxonomy.helper');
  $options = $taxonomy_helper->getSelectableBundles();
  $form['allowed_entity_types'] = [
    '#type' => 'checkboxes',
    '#options' => $options,
    '#title' => t('Allowed entity types'),
  ];

  $form['widget_type'] = [
    '#title' => t('Form element type'),
    '#type' => 'radios',
    '#options' => TaxonomyTermsWidget::getWidgetTypes(),
  ];
  if (!empty($form['vid']['#default_value'])) {
    $vocabulary_settings = $taxonomy_helper->getVocabularySettings($form['vid']['#default_value']);
  }
  if (!empty($vocabulary_settings)) {
    $form['allowed_entity_types']['#default_value'] = $vocabulary_settings['allowed_vocabulary_reference_types'];
    $form['widget_type']['#default_value'] = $vocabulary_settings['widget_type'];
  }
  else {
    $form['widget_type']['#default_value'] = CpTaxonomyHelper::WIDGET_TYPE_OPTIONS_SELECT;
  }
  $form['actions']['submit']['#submit'][] = 'cp_taxonomy_form_save_vocabulary_settings_submit';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter the terms overview page to fix links and redirects.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function cp_taxonomy_form_taxonomy_overview_terms_alter(array &$form, FormStateInterface &$form_state) {
  /** @var \Drupal\Core\StringTranslation\TranslatableMarkup $oldMarkup */
  $oldMarkup = $form['terms']['#empty'];
  /** @var \Drupal\taxonomy\VocabularyInterface $vocab */
  $vocab = $form_state->getStorage()['taxonomy']['vocabulary'];
  $arguments = [
    ':link' => Url::fromRoute('cp.taxonomy.term.add', ['taxonomy_vocabulary' => $vocab->id()])->toString(),
  ] + $oldMarkup->getArguments();
  $form['terms']['#empty'] = t($oldMarkup->getUntranslatedString(), $arguments);
  $form['actions']['reset_alphabetical']['#submit'][] = 'cp_taxonomy_reset_redirect';
}

/**
 * Redirect back to the page we were on previously.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function cp_taxonomy_reset_redirect(array &$form, FormStateInterface &$form_state) {
  /** @var \Drupal\taxonomy\VocabularyInterface $vocab */
  $vocab = $form_state->getStorage()['taxonomy']['vocabulary'];
  $form_state->setRedirect('cp.taxonomy.reset.vocab', ['vid' => $vocab->id()]);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Change the link for the Cancel button to stay in the cp namespace.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function cp_taxonomy_form_taxonomy_vocabulary_confirm_delete_alter(array &$form, FormStateInterface &$form_state) {
  if (\Drupal::routeMatch()->getRouteName() == 'cp.taxonomy.delete') {
    $form['actions']['cancel']['#url'] = Url::fromRoute('cp.taxonomy');
    $form['actions']['submit']['#submit'][] = 'cp_taxonomy_form_add_vocab_submit';
  }
}

/**
 * Redirect to the right place when done.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function cp_taxonomy_form_add_vocab_submit(array &$form, FormStateInterface &$form_state) {
  $form_state->setRedirect('cp.taxonomy');
}

/**
 * Save vocabulary settings submit handler.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function cp_taxonomy_form_save_vocabulary_settings_submit(array &$form, FormStateInterface &$form_state) {
  $vid = $form_state->getValue('vid');
  $settings['allowed_entity_types'] = $form_state->getValue('allowed_entity_types');
  $settings['widget_type'] = $form_state->getValue('widget_type');
  Drupal::service('cp.taxonomy.helper')->saveVocabularySettings($vid, $settings);
}

/**
 * Implements hook_views_data_alter().
 */
function cp_taxonomy_views_data_alter(&$data) {
  $data['taxonomy_term_field_data']['entity_bundle_to_vocabulary_vid'] = [
    'title' => t('Entity bundle to vocabulary vid'),
    'argument' => [
      'title' => t('Allowed vocabulary filter'),
      'help' => 'Convert entity bundle to vids',
      'field' => 'vid',
      'id' => 'entity_bundle_to_vocabulary_vid',
    ],
  ];
  $data['bibcite_reference']['cp_taxonomy_field_taxonomy_terms'] = [
    'title' => t('Reference Tag with terms'),
    'field' => [
      'title' => t('Reference Tag with terms'),
      'help' => t('Handle access by settings and current type.'),
      'id' => 'cp_taxonomy_field_taxonomy_terms',
    ],
  ];
  $data['node']['cp_taxonomy_node_field_taxonomy_terms'] = [
    'title' => t('Node Tag with terms (cp settings)'),
    'field' => [
      'title' => t('Node Tag with terms (cp settings)'),
      'help' => t('Handle access by settings.'),
      'id' => 'cp_taxonomy_node_field_taxonomy_terms',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Handle field_taxonomy_terms field visibility on node entity form.
 */
function cp_taxonomy_form_node_form_alter(&$form, FormStateInterface $form_state) {
  if (!empty($form['field_taxonomy_terms']['widget'])) {
    /** @var \Drupal\node\NodeForm $node_form */
    $node_form = $form_state->getBuildInfo()['callback_object'];
    $bundle = $node_form->getEntity()->bundle();
    $bundle_key = 'node:' . $bundle;

    $vocabularies = Drupal::service('cp.taxonomy.helper')->searchAllowedVocabulariesByType($bundle_key);
    // If the current node type has no related vocabularies, then hide it.
    if (empty($vocabularies)) {
      $form['field_taxonomy_terms']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Handle field_taxonomy_terms field visibility on publication form.
 */
function cp_taxonomy_form_bibcite_reference_form_alter(&$form, FormStateInterface $form_state) {
  if (!empty($form['field_taxonomy_terms']['widget'])) {
    $bundle_key = 'bibcite_reference:*';
    $vocabularies = Drupal::service('cp.taxonomy.helper')->searchAllowedVocabulariesByType($bundle_key);
    // If the current publication has no related vocabularies, then hide it.
    if (empty($vocabularies)) {
      $form['field_taxonomy_terms']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Handle field_taxonomy_terms field visibility on media entity form.
 */
function cp_taxonomy_form_media_form_alter(&$form, FormStateInterface $form_state) {
  if (!empty($form['field_taxonomy_terms']['widget'])) {
    $bundle_key = 'media:*';
    $vocabularies = Drupal::service('cp.taxonomy.helper')->searchAllowedVocabulariesByType($bundle_key);
    // If the current media has no related vocabularies, then hide it.
    if (empty($vocabularies)) {
      $form['field_taxonomy_terms']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_node_view_alter().
 */
function cp_taxonomy_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  /** @var \Drupal\cp_taxonomy\CpTaxonomyHelperInterface $cp_taxonomy_helper */
  $cp_taxonomy_helper = Drupal::service('cp.taxonomy.helper');
  $view_modes = [
    'full',
  ];
  $cp_taxonomy_helper->checkTaxonomyTermsPageVisibility($build, $view_modes);
  $cp_taxonomy_helper->checkTaxonomyTermsListingVisibility($build, 'node:' . $entity->bundle());
  $cp_taxonomy_helper->setCacheTags($build);
}

/**
 * Implements hook_bibcite_reference_view_alter().
 */
function cp_taxonomy_bibcite_reference_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  /** @var \Drupal\cp_taxonomy\CpTaxonomyHelperInterface $cp_taxonomy_helper */
  $cp_taxonomy_helper = Drupal::service('cp.taxonomy.helper');
  $view_modes = [
    'citation',
  ];
  $cp_taxonomy_helper->checkTaxonomyTermsPageVisibility($build, $view_modes);
  $cp_taxonomy_helper->checkTaxonomyTermsListingVisibility($build, 'bibcite_reference:*');
  $cp_taxonomy_helper->setCacheTags($build);
  // Override tags title.
  if (!empty($build['field_taxonomy_terms']['#title'])) {
    $build['field_taxonomy_terms']['#title'] = t('See also');
  }

}

/**
 * Implements hook_media_view_alter().
 */
function cp_taxonomy_media_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  /** @var \Drupal\cp_taxonomy\CpTaxonomyHelperInterface $cp_taxonomy_helper */
  $cp_taxonomy_helper = Drupal::service('cp.taxonomy.helper');
  $view_modes = [
    'full',
  ];
  $cp_taxonomy_helper->checkTaxonomyTermsPageVisibility($build, $view_modes);
  $cp_taxonomy_helper->checkTaxonomyTermsListingVisibility($build, 'media:*');
  $cp_taxonomy_helper->setCacheTags($build);
}

/**
 * Implements hook_entity_prepare_view().
 */
function cp_taxonomy_entity_prepare_view($entity_type_id, array $entities, array $displays, $view_mode) {
  /** @var \Drupal\vsite\Plugin\VsiteContextManager $vsite_context_manager */
  $vsite_context_manager = Drupal::service('vsite.context_manager');
  $group = $vsite_context_manager->getActiveVsite();
  if (empty($group)) {
    return;
  }
  /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
  foreach ($entities as $entity) {
    if (!$entity->hasField('field_taxonomy_terms')) {
      continue;
    }
    $field_values = $entity->get('field_taxonomy_terms')->getValue();
    if (empty($field_values)) {
      continue;
    }
    $entity->addCacheTags(['entity-with-taxonomy-terms:' . $group->id()]);
  }
}

/**
 * Implements hook_views_post_build().
 */
function cp_taxonomy_views_post_build(ViewExecutable $view) {
  /** @var \Drupal\vsite\Plugin\VsiteContextManager $vsite_context_manager */
  $vsite_context_manager = Drupal::service('vsite.context_manager');
  $group = $vsite_context_manager->getActiveVsite();
  if (empty($group)) {
    return;
  }
  // Tag all publications views, can't find better working solution.
  if ($view->id() == 'publications') {
    $view->storage->addCacheTags(['entity-with-taxonomy-terms:' . $group->id()]);
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function cp_taxonomy_taxonomy_vocabulary_access(EntityInterface $entity, $operation, AccountInterface $account) {

  /** @var \Drupal\vsite\Plugin\VsiteContextManager $vsite_manager */
  $vsite_manager = \Drupal::service('vsite.context_manager');
  /** @var \Drupal\group\Entity\GroupInterface $active_vsite */
  $active_vsite = $vsite_manager->getActiveVsite();

  // If in vsite context then only alter access.
  if ($active_vsite) {
    // If no permission don't show operations buttons.
    if (!$active_vsite->hasPermission('manage taxonomy', $account)) {
      return AccessResult::forbidden();
    }
    return AccessResult::allowed();
  }
  // If no active vsite no opinion.
  return AccessResult::neutral();
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function cp_taxonomy_taxonomy_term_access(EntityInterface $entity, $operation, AccountInterface $account) {

  /** @var \Drupal\vsite\Plugin\VsiteContextManager $vsite_manager */
  $vsite_manager = \Drupal::service('vsite.context_manager');
  /** @var \Drupal\group\Entity\GroupInterface $active_vsite */
  $active_vsite = $vsite_manager->getActiveVsite();

  $plugin_id = "group_entity:{$entity->getEntityTypeId()}";

  // If in vsite context then only alter access.
  if ($active_vsite) {
    // If no permission don't show operations buttons and other form buttons.
    if (!$active_vsite->hasPermission("$operation any $plugin_id entity", $account)) {
      return AccessResult::forbidden();
    }
    return AccessResult::allowed();
  }
  // If no active vsite no opinion.
  return AccessResult::neutral();
}
