<?php

/**
 * Implements hook_block_view_alter().
 *
 * Hides the search bar title display.
 */
function hwpi_block_view_alter(&$render, $block) {
  if ($block->delta == 'site-search' && _is_hwpi_theme()) {
    unset($render['content']['search_block_form']['#title_display']);
  }
}

/**
 * Implements hook_node_insert().
 */
function hwpi_node_insert($node) {
  // Only continues if the new node is an OG group type.
  if (!og_is_group_type('node', $node->type)) {
    return;
  }

  $vsite = vsite_get_vsite($node->nid);

  if (module_exists('salesforce')) {
    //PURL is needed but spaces_og_node_insert may not have fired yet
    if (!isset($vsite->group->purl) && is_array($node->purl) && !empty($node->purl['value'])) {
      $vsite->group->purl = $node->purl['value'];
    }

    module_load_include('inc', 'hwpi', 'includes/salesforce');
    hwpi_salesforce_impl_project_create($vsite, $vsite->group->uid);
    hwpi_salesforce_support_project_create($vsite, $vsite->group->uid);
  }

  // Only continues to alter settings if the site's theme is HWPI.
  $theme = $vsite->controllers->variable->get('theme_default');
  if (!_is_hwpi_theme($theme)) {
    return;
  }

  // Sets all HWPI-theme-specific variable defaults.
  hwpi_theme_set_defaults();
}

/**
 * Implements hook_form_FORM_ID_alter() for cp_appearance_theme_picker_form.
 */
function hwpi_form_cp_appearance_theme_picker_form_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'hwpi_theme_picker_form_submit';
}

/**
 * Submit callback for cp_appearance_theme_picker_form.
 */
function hwpi_theme_picker_form_submit($form, &$form_state) {
  // Only continues if a theme value is set.
  if (!isset($form_state['values']['theme_default'])) {
    return;
  }

  // Only continues if the selected theme is HWPI.
  $selected_theme = $form_state['values']['theme_default'];
  if (!_is_hwpi_theme($selected_theme)) {
    return;
  }

  // Sets all HWPI-theme-specific variable defaults.
  hwpi_theme_set_defaults();
}

/**
 * Sets all HWPI-theme-specific variable defaults.
 *
 * @see hwpi_form_cp_appearance_theme_picker_form_alter()
 * @see
 */
function hwpi_theme_set_defaults() {
  // Declares settings specific to HWPI themes.
  $settings = array(
    'os_breadcrumbs_show_breadcrumbs' => 1,
    'enable_responsive' => 1,
  );

  // Sets all HWPI-theme-specific settings.
  foreach ($settings as $name => $value) {
    if ($space = spaces_get_space()) {
      $space->controllers->variable->set($name, $value);
    }
    else {
      variable_set($name, $value);
    }
  }
}



/**
 * Implements hook_form_FORM_ID_alter().
 */
function hwpi_form_user_login_alter(&$form, $form_state) {
  $form['message'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'user-login-message-text',
      )
    ),
    'message-text' => array(
      '#markup' => t('!roadmap-link for the latest new feature and bug fix information.', array(
        '!roadmap-link' => l('Visit our roadmap', 'http://theopenscholar.org/roadmap')
      ))
    )
  );
}
